version: "3.8"

services:
  cvt-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: nginx-data
        target: /usr/share/nginx/html

volumes:
  nginx-data:
